Migrate Redshift virtual schema to its own repository
exasol/redshift-virtual-schema pull request #2
Opened 2021-01-15 13:04 UTC by chiaradiamarcelo

Closes #1.

2021-01-15 14:45 UTC, AnastasiiaSergienko requested changes

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on .travis.yml
> +sudo: required
I think we don't need this because we don't have integration tests

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on README.md
> +The **Redshift Virtual Schema** provides an abstraction layer that makes an external [AWS Redshift](https://aws.amazon.com/redshift/) data source accessible from an Exasol database through regular SQ
```suggestion
The **Redshift Virtual Schema** provides an abstraction layer that makes an external [AWS Redshift](https://aws.amazon.com/redshift/) data source accessible from an Exasol database through regular SQL commands. The contents of the external AWS Redshift data source are mapped to virtual tables which look like and can be queried as any regular Exasol table.
```

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on README.md
> +* Access a AWS Redshitf data source in read only mode from an Exasol database, using a Virtual Schema.
```suggestion
* Access an AWS Redshift data source in read-only mode from an Exasol database, using a Virtual Schema.
```

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on README.md
> +| [Exasol Hamcrest Result Set Matcher][exasol-hamcrest]              | Hamcrest result set matcher for testing                | MIT License                   |
Is it used here? I think this is for integration tests

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on doc/changes/changes_1.0.0.md
> +# RedShift Virtual Schema 1.0.0, released 2021-01-15
```suggestion
# Redshift Virtual Schema 1.0.0, released 2021-01-15
```

2021-01-15 14:45 UTC, AnastasiiaSergienko commented on pom.xml
> +	<name>Virtual Schema for RedShift</name>
```suggestion
	<name>Virtual Schema for Redshift</name>
```

2021-01-16 13:50 UTC, chiaradiamarcelo commented on doc/changes/changes_1.0.0.md
> +# Redshift Virtual Schema 1.0.0, released 2021-01-15
```suggestion
# Redshift Virtual Schema 1.0.0, released 2021-01-18
```

2021-01-18 08:09 UTC, AnastasiiaSergienko approved these changes

2021-01-18 08:10 UTC, merged